services:
  - type: web
    name: FunDraw_ChemLab
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHON_VERSION
        value: 3.9.18
